name: Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Replace password in config.yaml
        run: |
          sed -i "s|password:.*|password: '${{ secrets.DB_PASSWORD }}'|" config.yaml
        env:
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
